$axure.loadCurrentPage({
  "url":"算税费的历史记录.html",
  "generationDate":new Date(1481800603019.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9226d46e31094a0db2fe26a53ee6cf20",
    "type":"Axure:Page",
    "name":"算税费的历史记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"214b45f6410e4c339514c85d9e9d97c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":42},
            "size":{
              "width":347,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f4cd4861504a939d8afc954ecc4ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":42},
                "size":{
                  "width":347,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u0.png"}},
{
          "id":"fe37d392bcd646f0a836adeb896c1034",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":49,
              "y":42},
            "size":{
              "width":347,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f02bca3e5d46fdaaf6eda82975efb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":49,
                  "y":42},
                "size":{
                  "width":347,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u2.png"}},
{
          "id":"75b92836be6c47018c1a791111add316",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":49,
              "y":126},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97d2b928d743498a8fdea4ba771033a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":49,
                  "y":126},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看历史的税费计算",
                      "target":{
                        "targetType":"page",
                        "url":"查看历史的税费计算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"6f4c62ea7400476ea091aaa70dc50d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":372,
              "y":154},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66380ff64c11483d909e9709d446a6b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":372,
                  "y":154},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68a6f57020d04d34800e52a6a0f4e05c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":64,
              "y":155},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"292c383d72a04b2d93659ff993811df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":155},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15047a65bb854af2840b5cf337a89775",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":63,
              "y":132},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468ad71434964689b78c03aafc9416da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":63,
                  "y":132},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d83205365c741bda87b5722f49e5ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":63,
              "y":176},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb4aa53a0bf049c182b5096cffc5b131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":176},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53ab5d24e76f4fb8a4122c0e43766f08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":49,
              "y":203},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f67e091236b6474dbe9516f4c7db8de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":49,
                  "y":203},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看历史的税费计算",
                      "target":{
                        "targetType":"page",
                        "url":"查看历史的税费计算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"586da5359b934f05af576eb124a98066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":372,
              "y":231},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c42c5342237c4a9bac09844e923cefd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":372,
                  "y":231},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf8ddc80ee8d42c5964d08b8f52ba5bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":64,
              "y":233},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"902e7d8c3e764efb81f0b7f3e162229f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":233},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8b6aa3ddd894f8eabe3fba2bd049790",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":63,
              "y":210},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1198fb6c32e0413c8790e1f402d3cd89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":63,
                  "y":210},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea8eb5bb366448438c73b5c2d548e0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":63,
              "y":254},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ee147507554055a5e28f239f877448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":254},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6886a03c184e83bd66d88572cc80cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":49,
              "y":280},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd0d7b4fa54146f28d6c050637c2d309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":49,
                  "y":280},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看历史的税费计算",
                      "target":{
                        "targetType":"page",
                        "url":"查看历史的税费计算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"f8272ceadb464613b503c7988dfd5d54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":372,
              "y":308},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b00982eeabf42ac957b13fb9fe10e27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":372,
                  "y":308},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd79be551eb14113a0bc02bce33b4509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":64,
              "y":311},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f4b947a4843477b913c1b9d0e5b3afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":311},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14d2b9af43344827895357ff3d9a3c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":63,
              "y":288},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236dfbebf5fb46a0a56858e480ee55c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":63,
                  "y":288},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07a13fddf0d848c698d77c272168c3a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":63,
              "y":332},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1b53dfbea940c4b0f10ceb76a47ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":332},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9480d9d7feab41d88c798b027da44ba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":67,
              "y":90},
            "size":{
              "width":310,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9aeaddd04b45d5a41c2ebae1a60a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":67,
                  "y":90},
                "size":{
                  "width":310,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "214b45f6410e4c339514c85d9e9d97c6":{
      "scriptId":"u0"},
    "83f4cd4861504a939d8afc954ecc4ab8":{
      "scriptId":"u1"},
    "fe37d392bcd646f0a836adeb896c1034":{
      "scriptId":"u2"},
    "23f02bca3e5d46fdaaf6eda82975efb4":{
      "scriptId":"u3"},
    "75b92836be6c47018c1a791111add316":{
      "scriptId":"u4"},
    "97d2b928d743498a8fdea4ba771033a3":{
      "scriptId":"u5"},
    "6f4c62ea7400476ea091aaa70dc50d0e":{
      "scriptId":"u6"},
    "66380ff64c11483d909e9709d446a6b0":{
      "scriptId":"u7"},
    "68a6f57020d04d34800e52a6a0f4e05c":{
      "scriptId":"u8"},
    "292c383d72a04b2d93659ff993811df4":{
      "scriptId":"u9"},
    "15047a65bb854af2840b5cf337a89775":{
      "scriptId":"u10"},
    "468ad71434964689b78c03aafc9416da":{
      "scriptId":"u11"},
    "5d83205365c741bda87b5722f49e5ad0":{
      "scriptId":"u12"},
    "eb4aa53a0bf049c182b5096cffc5b131":{
      "scriptId":"u13"},
    "53ab5d24e76f4fb8a4122c0e43766f08":{
      "scriptId":"u14"},
    "f67e091236b6474dbe9516f4c7db8de6":{
      "scriptId":"u15"},
    "586da5359b934f05af576eb124a98066":{
      "scriptId":"u16"},
    "c42c5342237c4a9bac09844e923cefd7":{
      "scriptId":"u17"},
    "cf8ddc80ee8d42c5964d08b8f52ba5bd":{
      "scriptId":"u18"},
    "902e7d8c3e764efb81f0b7f3e162229f":{
      "scriptId":"u19"},
    "d8b6aa3ddd894f8eabe3fba2bd049790":{
      "scriptId":"u20"},
    "1198fb6c32e0413c8790e1f402d3cd89":{
      "scriptId":"u21"},
    "ea8eb5bb366448438c73b5c2d548e0e3":{
      "scriptId":"u22"},
    "92ee147507554055a5e28f239f877448":{
      "scriptId":"u23"},
    "3e6886a03c184e83bd66d88572cc80cf":{
      "scriptId":"u24"},
    "bd0d7b4fa54146f28d6c050637c2d309":{
      "scriptId":"u25"},
    "f8272ceadb464613b503c7988dfd5d54":{
      "scriptId":"u26"},
    "7b00982eeabf42ac957b13fb9fe10e27":{
      "scriptId":"u27"},
    "cd79be551eb14113a0bc02bce33b4509":{
      "scriptId":"u28"},
    "7f4b947a4843477b913c1b9d0e5b3afa":{
      "scriptId":"u29"},
    "14d2b9af43344827895357ff3d9a3c5d":{
      "scriptId":"u30"},
    "236dfbebf5fb46a0a56858e480ee55c7":{
      "scriptId":"u31"},
    "07a13fddf0d848c698d77c272168c3a4":{
      "scriptId":"u32"},
    "4e1b53dfbea940c4b0f10ceb76a47ed2":{
      "scriptId":"u33"},
    "9480d9d7feab41d88c798b027da44ba4":{
      "scriptId":"u34"},
    "3f9aeaddd04b45d5a41c2ebae1a60a5f":{
      "scriptId":"u35"}}});