$axure.loadCurrentPage({
  "url":"查询历史记录列表.html",
  "generationDate":new Date(1481800603674.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aa79fd9415de4b0a872f77f8d02a5d55",
    "type":"Axure:Page",
    "name":"查询历史记录列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41b9e71696024eb1810ad3ef23c95322",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ae0899a32342c89020d65dffec94b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询历史记录页面/u0.png"}},
{
          "id":"696ec6c9d4e242018a32988b3c7879f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7201ea184ee34042977cc4188674f9ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询历史记录页面/u2.png"}},
{
          "id":"2eb202b7335745ce97bf11559c5851e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":43,
              "y":114},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531c38fd2dcc4c0ab6becbb8834d562c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":43,
                  "y":114},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 二次确认弹框 to 展示弹框",
                      "panelsToStates":[{
                          "panelPath":["41059f2d9ee9444797456d0fa0160842"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"5a75ca753cef43d8b05e3b4a344d3a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":366,
              "y":142},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426c50d87b0d483d9a2531f95bc3f6a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":366,
                  "y":142},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f212404b352d4494a17533a7a56be915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":58,
              "y":143},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dea923fec5c47bbb10807210eaa1682",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":143},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89ae623201f343309f46691d47d25c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":120},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe7ec058d0b4c36a79ee810b5d3095a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":120},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c82772abc7074bb28155b0f87f0cadea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":57,
              "y":164},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"891678cb7eb348da8552407de6c73320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":164},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fee23dbc41664c02b19555537016fcaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":43,
              "y":191},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083b1045ffa34076aa8d8fa6dff12d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":43,
                  "y":191},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"f87e6140b3614452a06e05ef1e8f2708",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":43,
              "y":268},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c66c01e8907f44b18d175a4058610327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":43,
                  "y":268},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"5117d2831abc48488c8c33fceff40c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":58,
              "y":299},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20fb69d6b1664e9cb5e73e6370e26042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":299},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12c4be751c50493b8066e94c3398af6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":276},
            "size":{
              "width":241,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b9853c6eddf46b2bddcecd6a6f4843e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":276},
                "size":{
                  "width":241,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f67c33c933b495187016b619eade70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":57,
              "y":320},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e889eb2fbace4c96b8041d97989d4caf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":320},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78e2411cabc647ed91191b3e5408a27c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":61,
              "y":78},
            "size":{
              "width":310,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a61550b624804fd6a4b84cbe9829f0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":61,
                  "y":78},
                "size":{
                  "width":310,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8938974d3d63495e8f7c6a28f5874341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":147},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e7f024c216c49c5a0afefb27cd6ef30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":147},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb55109d5d1941e187356f2eb9af7202",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":366,
              "y":294},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fad45bf0644bc5ba03aa5dbf38c8de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":366,
                  "y":294},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4a245eca7e49f9ad95b5fd7d596b5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":299},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b28041df0094e6aac02bd134ab093fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":299},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0fed9d0a61f4e1a96bcea5288df0040",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":43,
              "y":345},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b1b1570b5154d748f4904f62a3309a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":43,
                  "y":345},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"403f89d0765e43e6a92be31ae588eb61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":58,
              "y":376},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c165ffb3f574786a7f0b45cebb8bc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":376},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"274aa59c514c4280b95a56d59e8a8a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":353},
            "size":{
              "width":241,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad9576782554b8dac9de18094b64c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":353},
                "size":{
                  "width":241,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67dbc589e01b44829e237edc89bf55ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":57,
              "y":397},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad72cfb4c64a405eaf20027a9fb3ada8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":397},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40cf571bf72a4db5bcc7ccd170fccbc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":366,
              "y":371},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef691fe68cfa402d868211196b02f344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":366,
                  "y":371},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6b29702fece473bb4ab9a34e48698ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":376},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce3eb8f5a0f479896be3f1048da7902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":376},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41059f2d9ee9444797456d0fa0160842",
          "label":"二次确认弹框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":53.5,
              "y":171},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"23aef2bade16468981c7d0836a65ed40",
              "label":"隐藏弹框",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"86aa7dee03614ca196602a2521aa8b2e",
              "label":"展示弹框",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"76b94f8843d54622b81831a3bd5fc989",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":326,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07d1acdbcb3e446097d18b920081229e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":326,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查询历史记录页面/u37.png"}},
{
                  "id":"52cc53ca15ec43e983430e082b38d62e",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"17px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":32,
                      "y":91},
                    "size":{
                      "width":262,
                      "height":41},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa79f6f3b2fa42769a03f6a08569d953",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"17px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":32,
                          "y":91},
                        "size":{
                          "width":262,
                          "height":41},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c03d149f25544a94aea21a2bcdb1a97b",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":20,
                      "y":148},
                    "size":{
                      "width":145,
                      "height":52}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65f1a391e9114b6eacb3c77f4d879212",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":20,
                          "y":148},
                        "size":{
                          "width":145,
                          "height":52}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 二次确认弹框 to 隐藏弹框",
                              "panelsToStates":[{
                                  "panelPath":["41059f2d9ee9444797456d0fa0160842"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/查询历史记录页面/u41.png"}},
{
                  "id":"080796cd3f634a13a35ef789c08adfdf",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Droid Sans Regular', 'Droid Sans'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":32,
                      "y":164},
                    "size":{
                      "width":120,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de06da29b63a40a2bdf25398143d15f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Droid Sans Regular', 'Droid Sans'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":32,
                          "y":164},
                        "size":{
                          "width":120,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3718c9badb3046bbaa1c852d90cfd524",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":162,
                      "y":148},
                    "size":{
                      "width":145,
                      "height":52}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6dd0ed03e5f4d36b68c2e64685b9c35",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":162,
                          "y":148},
                        "size":{
                          "width":145,
                          "height":52}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 稍后返回结果",
                              "target":{
                                "targetType":"page",
                                "url":"稍后返回结果.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/查询历史记录页面/u41.png"}},
{
                  "id":"61f34ebf96804696842679561a20319e",
                  "label":"",
                  "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Droid Sans Regular', 'Droid Sans'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":181,
                      "y":164},
                    "size":{
                      "width":110,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13f52d31d4c849d3999e5e749b9b7e89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"41059f2d9ee9444797456d0fa0160842",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Droid Sans Regular', 'Droid Sans'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":181,
                          "y":164},
                        "size":{
                          "width":110,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"14979347672f4a09b9d472a7623fc305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":43,
              "y":191},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76102aa5445745dfa261933ff0584c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":43,
                  "y":191},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 二次确认弹框 to 展示弹框",
                      "panelsToStates":[{
                          "panelPath":["41059f2d9ee9444797456d0fa0160842"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"68a84f818620465ab4876fcad41017a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":58,
              "y":221},
            "size":{
              "width":203,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cc4da215d454b29848648145ad80189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":221},
                "size":{
                  "width":203,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54b074df3aad412b802eda01aab4db2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":198},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089f312c8ca14531b5fd870dd940c3f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":198},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75e922b5668c4fccab55c40c2305637f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":57,
              "y":242},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1191e5e4b894d2d8f66bbdac43865e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":242},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09c32bc21b224b6e85bf247cc2bd3ee7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":366,
              "y":217},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa02878680b4eaa87295dbfbca67508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":366,
                  "y":217},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc1f120f958341eb8366ec369f62a304",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":222},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0aa4f3d30a34045ac0da5478ea00ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":222},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "41b9e71696024eb1810ad3ef23c95322":{
      "scriptId":"u0"},
    "d3ae0899a32342c89020d65dffec94b6":{
      "scriptId":"u1"},
    "696ec6c9d4e242018a32988b3c7879f9":{
      "scriptId":"u2"},
    "7201ea184ee34042977cc4188674f9ae":{
      "scriptId":"u3"},
    "2eb202b7335745ce97bf11559c5851e0":{
      "scriptId":"u4"},
    "531c38fd2dcc4c0ab6becbb8834d562c":{
      "scriptId":"u5"},
    "5a75ca753cef43d8b05e3b4a344d3a06":{
      "scriptId":"u6"},
    "426c50d87b0d483d9a2531f95bc3f6a4":{
      "scriptId":"u7"},
    "f212404b352d4494a17533a7a56be915":{
      "scriptId":"u8"},
    "3dea923fec5c47bbb10807210eaa1682":{
      "scriptId":"u9"},
    "89ae623201f343309f46691d47d25c73":{
      "scriptId":"u10"},
    "bbe7ec058d0b4c36a79ee810b5d3095a":{
      "scriptId":"u11"},
    "c82772abc7074bb28155b0f87f0cadea":{
      "scriptId":"u12"},
    "891678cb7eb348da8552407de6c73320":{
      "scriptId":"u13"},
    "fee23dbc41664c02b19555537016fcaa":{
      "scriptId":"u14"},
    "083b1045ffa34076aa8d8fa6dff12d78":{
      "scriptId":"u15"},
    "f87e6140b3614452a06e05ef1e8f2708":{
      "scriptId":"u16"},
    "c66c01e8907f44b18d175a4058610327":{
      "scriptId":"u17"},
    "5117d2831abc48488c8c33fceff40c6b":{
      "scriptId":"u18"},
    "20fb69d6b1664e9cb5e73e6370e26042":{
      "scriptId":"u19"},
    "12c4be751c50493b8066e94c3398af6c":{
      "scriptId":"u20"},
    "8b9853c6eddf46b2bddcecd6a6f4843e":{
      "scriptId":"u21"},
    "1f67c33c933b495187016b619eade70b":{
      "scriptId":"u22"},
    "e889eb2fbace4c96b8041d97989d4caf":{
      "scriptId":"u23"},
    "78e2411cabc647ed91191b3e5408a27c":{
      "scriptId":"u24"},
    "a61550b624804fd6a4b84cbe9829f0b5":{
      "scriptId":"u25"},
    "8938974d3d63495e8f7c6a28f5874341":{
      "scriptId":"u26"},
    "0e7f024c216c49c5a0afefb27cd6ef30":{
      "scriptId":"u27"},
    "eb55109d5d1941e187356f2eb9af7202":{
      "scriptId":"u28"},
    "e0fad45bf0644bc5ba03aa5dbf38c8de":{
      "scriptId":"u29"},
    "cb4a245eca7e49f9ad95b5fd7d596b5d":{
      "scriptId":"u30"},
    "5b28041df0094e6aac02bd134ab093fb":{
      "scriptId":"u31"},
    "b0fed9d0a61f4e1a96bcea5288df0040":{
      "scriptId":"u32"},
    "2b1b1570b5154d748f4904f62a3309a6":{
      "scriptId":"u33"},
    "403f89d0765e43e6a92be31ae588eb61":{
      "scriptId":"u34"},
    "1c165ffb3f574786a7f0b45cebb8bc72":{
      "scriptId":"u35"},
    "274aa59c514c4280b95a56d59e8a8a4b":{
      "scriptId":"u36"},
    "8ad9576782554b8dac9de18094b64c8c":{
      "scriptId":"u37"},
    "67dbc589e01b44829e237edc89bf55ef":{
      "scriptId":"u38"},
    "ad72cfb4c64a405eaf20027a9fb3ada8":{
      "scriptId":"u39"},
    "40cf571bf72a4db5bcc7ccd170fccbc0":{
      "scriptId":"u40"},
    "ef691fe68cfa402d868211196b02f344":{
      "scriptId":"u41"},
    "f6b29702fece473bb4ab9a34e48698ba":{
      "scriptId":"u42"},
    "0ce3eb8f5a0f479896be3f1048da7902":{
      "scriptId":"u43"},
    "41059f2d9ee9444797456d0fa0160842":{
      "scriptId":"u44"},
    "76b94f8843d54622b81831a3bd5fc989":{
      "scriptId":"u45"},
    "07d1acdbcb3e446097d18b920081229e":{
      "scriptId":"u46"},
    "52cc53ca15ec43e983430e082b38d62e":{
      "scriptId":"u47"},
    "fa79f6f3b2fa42769a03f6a08569d953":{
      "scriptId":"u48"},
    "c03d149f25544a94aea21a2bcdb1a97b":{
      "scriptId":"u49"},
    "65f1a391e9114b6eacb3c77f4d879212":{
      "scriptId":"u50"},
    "080796cd3f634a13a35ef789c08adfdf":{
      "scriptId":"u51"},
    "de06da29b63a40a2bdf25398143d15f2":{
      "scriptId":"u52"},
    "3718c9badb3046bbaa1c852d90cfd524":{
      "scriptId":"u53"},
    "f6dd0ed03e5f4d36b68c2e64685b9c35":{
      "scriptId":"u54"},
    "61f34ebf96804696842679561a20319e":{
      "scriptId":"u55"},
    "13f52d31d4c849d3999e5e749b9b7e89":{
      "scriptId":"u56"},
    "14979347672f4a09b9d472a7623fc305":{
      "scriptId":"u57"},
    "76102aa5445745dfa261933ff0584c00":{
      "scriptId":"u58"},
    "68a84f818620465ab4876fcad41017a6":{
      "scriptId":"u59"},
    "1cc4da215d454b29848648145ad80189":{
      "scriptId":"u60"},
    "54b074df3aad412b802eda01aab4db2c":{
      "scriptId":"u61"},
    "089f312c8ca14531b5fd870dd940c3f4":{
      "scriptId":"u62"},
    "75e922b5668c4fccab55c40c2305637f":{
      "scriptId":"u63"},
    "f1191e5e4b894d2d8f66bbdac43865e4":{
      "scriptId":"u64"},
    "09c32bc21b224b6e85bf247cc2bd3ee7":{
      "scriptId":"u65"},
    "bfa02878680b4eaa87295dbfbca67508":{
      "scriptId":"u66"},
    "cc1f120f958341eb8366ec369f62a304":{
      "scriptId":"u67"},
    "d0aa4f3d30a34045ac0da5478ea00ae1":{
      "scriptId":"u68"}}});