$axure.loadCurrentPage({
  "url":"微信通知查询结果-查询失败.html",
  "generationDate":new Date(1481800603354.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5948720850a34b90b661312c5d2a2b5d",
    "type":"Axure:Page",
    "name":"微信通知查询结果-查询失败",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"06797d54d14c4c28b4c3b08d13c3eb13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":30},
            "size":{
              "width":506,
              "height":865}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fd10ea1146a420e817b886fdff3195f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":30},
                "size":{
                  "width":506,
                  "height":865}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果-查询成功/u0.png"}},
{
          "id":"636266b131e34eecbf966f7bc56d3a03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":300},
            "size":{
              "width":466,
              "height":238},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd2c83e4c0b34d3996d8bcfdfa9cea2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":300},
                "size":{
                  "width":466,
                  "height":238},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果-查询失败/u2.png"}},
{
          "id":"985c05058dc34d72aa7868dcaaaaa8d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":530},
            "size":{
              "width":466,
              "height":30},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e319e47f7d74bb3856e5bd0d716278a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":530},
                "size":{
                  "width":466,
                  "height":30},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果-查询失败/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "06797d54d14c4c28b4c3b08d13c3eb13":{
      "scriptId":"u0"},
    "1fd10ea1146a420e817b886fdff3195f":{
      "scriptId":"u1"},
    "636266b131e34eecbf966f7bc56d3a03":{
      "scriptId":"u2"},
    "cd2c83e4c0b34d3996d8bcfdfa9cea2a":{
      "scriptId":"u3"},
    "985c05058dc34d72aa7868dcaaaaa8d4":{
      "scriptId":"u4"},
    "7e319e47f7d74bb3856e5bd0d716278a":{
      "scriptId":"u5"}}});