$axure.loadCurrentPage({
  "url":"输入房产信息.html",
  "generationDate":new Date(1481800602860.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d8a30425be64634a95cacb336121b64",
    "type":"Axure:Page",
    "name":"输入房产信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"114ad75a1375493a94131185c647d81e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":71},
            "size":{
              "width":347,
              "height":659}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a623743494a54edf86050801e6fa8eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":71},
                "size":{
                  "width":347,
                  "height":659}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u0.png"}},
{
          "id":"b95bd6569f3f492398f93d417295c6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":44,
              "y":71},
            "size":{
              "width":347,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0b49fc31cb44bab557e00c2e0ef58f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":44,
                  "y":71},
                "size":{
                  "width":347,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u2.png"}},
{
          "id":"be20b843bf68408abe8df554960f5bfa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":88,
              "y":200},
            "size":{
              "width":181,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a964935de9b142ffae887aee33cb027b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":266},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a54cee5bfceb4693b3ee11dc4acf1ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":266},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6a77ef44c3743428753d0b3e46da152",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":266},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99c8c55f48764d12a5f1212c779ade12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":266},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 原登记价 to 隐藏",
                      "panelsToStates":[{
                          "panelPath":["15ab70087088413da77f18edcc44fa4d"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"a3062701ac98475583f659a561dc2338",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":289},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b7108dbbc849928cd604788b6fd2f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":289},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 原登记价 to 展示",
                      "panelsToStates":[{
                          "panelPath":["15ab70087088413da77f18edcc44fa4d"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"50379e64b86f486a99017eb80d88e345",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":108,
              "y":608},
            "size":{
              "width":222,
              "height":37}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 计算结果",
                      "target":{
                        "targetType":"page",
                        "url":"计算结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0084a714a1024256b79c9e60c6c252c9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":157,
              "y":129},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c576f0eebe414792915ad85bad37f251",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":132},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed59fcfcf87d464780f4a242097966fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":132},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"245f7e15eee242e2aa195859e25f6f5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":204},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bf9cdbd7e8a4f318f277ab473893234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":204},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"370c4666cbca4e75b7e58ad973a7ee09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":228},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b6818a93394172bf6ea78c5f129fa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":228},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e0e922127a947e498bfd194da68bcf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":366},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25a585acc73b4b1cbce40b1fc5343766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":366},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9118d673f63940a3acb11ff0e1d26e29",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":366},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6607273a257c4dc2a86740de1c001046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":366},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6c786f17d92143c2b67b29ffdafb6f27",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":389},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4fe0c72647542e8b4fc3fad47156979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":389},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c9fb518bce9d481abe03254425c01d74",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":410},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c7696f3b78e4cd1bc4b913f4d4e0aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":410},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"571bb045d81f4100b8bd326dd3836ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":441},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f509475a7444cd2b158a2e6ebd862d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":441},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a657e099e174e34ace127ba917463c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":514},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d11f18e66641279f17d26133e82f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":514},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51810f8b8f46487ea4544f96d04ec3fd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":514},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1fe80ab313544869d3c3e9607a1671e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":514},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0e112c1170314113b144b3b49ea16745",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":514},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950251552b144a1eb8f359b6be8b0238",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":514},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a27418e88a4e413c93f1c950b9c59b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":130,
              "y":570},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd52a9b7abf74844a657994f3659442c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":570},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38a9b1ed89354b33a01cb7800ae1d218",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":186,
              "y":667},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c0e1eef53d3447295b4eb8f607c8322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":186,
                  "y":667},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 算税费的历史记录",
                      "target":{
                        "targetType":"page",
                        "url":"算税费的历史记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcf0d0af149348a0986a4533cf63aca4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":88,
              "y":161},
            "size":{
              "width":181,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cee38a3a6a574e63b3b79a19ea6f3c97",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":439},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15d3bc2c95b4fccb4944d20e7fa0cbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":439},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"987b56868c814d4f870c0102b99ef9c8",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":462},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5246ec32c0841c0a675b63e241d2936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":462},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"343d7edc821b465d8be3b67b84b7ff4a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":483},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a4ac70f6dd74bdfb5a2a270e8c905e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":483},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"15ab70087088413da77f18edcc44fa4d",
          "label":"原登记价",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":319},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"aca19644c0b14dc78e80f366bad3755d",
              "label":"隐藏",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"7925a1b6dab04b029a92d87e413dbdeb",
              "label":"展示",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b4bd62ec9435484a89cf4886dd85d86a",
                  "label":"",
                  "parentDynamicPanel":"15ab70087088413da77f18edcc44fa4d",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"f30d69caf2d345d98339b723656ee466",
                  "label":"",
                  "parentDynamicPanel":"15ab70087088413da77f18edcc44fa4d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":4},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"483e5a6c595b442fb08ca7c912e8db86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"15ab70087088413da77f18edcc44fa4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":4},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a9c6ffb453c7449f84f91d32ec5cc757",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0x26000000},
            "location":{
              "x":413,
              "y":99},
            "size":{
              "width":207,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e705852cee54d1482e9996c1c8c15dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0x26000000},
                "location":{
                  "x":413,
                  "y":99},
                "size":{
                  "width":207,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u50.png"}},
{
          "id":"fafc5e4330e148a2821896ac6b40b8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":412,
              "y":95},
            "size":{
              "width":207,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bbb9807c76f43a0a35e9a4980911adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":412,
                  "y":95},
                "size":{
                  "width":207,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u52.png"}},
{
          "id":"f5c4fc15d9014a998f061b2cada42d36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":250,
              "y":125},
            "size":{
              "width":164,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43dc435dc2314f829c39bd52e9f39f55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":250,
                  "y":125},
                "size":{
                  "width":164,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u54.png"}},
{
          "id":"5000f62f696d41868cce6c291b33d5ab",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":404,
              "y":126},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/输入房产信息/u56_line.png"}},
{
          "id":"420aff8a5d484b4cbbeaaf5844065f10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0x26000000},
            "location":{
              "x":463,
              "y":562},
            "size":{
              "width":207,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07653451f07b40f0ba12736d820f68ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0x26000000},
                "location":{
                  "x":463,
                  "y":562},
                "size":{
                  "width":207,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u57.png"}},
{
          "id":"c0ffa053453b41cf8d3b4d744873ed90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":462,
              "y":560},
            "size":{
              "width":207,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de267fa08ed64baba029a0a1f30a62e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":462,
                  "y":560},
                "size":{
                  "width":207,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u59.png"}},
{
          "id":"4d5344a666f647f5b1b9a038877140e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":300,
              "y":563},
            "size":{
              "width":164,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ae931178bc94e038d7b498e01f42cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":300,
                  "y":563},
                "size":{
                  "width":164,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u54.png"}},
{
          "id":"c6242164575742a69e6b3cc1fb2211c0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":454,
              "y":564},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/输入房产信息/u56_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "114ad75a1375493a94131185c647d81e":{
      "scriptId":"u0"},
    "a623743494a54edf86050801e6fa8eb4":{
      "scriptId":"u1"},
    "b95bd6569f3f492398f93d417295c6a1":{
      "scriptId":"u2"},
    "1d0b49fc31cb44bab557e00c2e0ef58f":{
      "scriptId":"u3"},
    "be20b843bf68408abe8df554960f5bfa":{
      "scriptId":"u4"},
    "a964935de9b142ffae887aee33cb027b":{
      "scriptId":"u5"},
    "a54cee5bfceb4693b3ee11dc4acf1ed1":{
      "scriptId":"u6"},
    "a6a77ef44c3743428753d0b3e46da152":{
      "scriptId":"u7"},
    "99c8c55f48764d12a5f1212c779ade12":{
      "scriptId":"u8"},
    "a3062701ac98475583f659a561dc2338":{
      "scriptId":"u9"},
    "94b7108dbbc849928cd604788b6fd2f6":{
      "scriptId":"u10"},
    "50379e64b86f486a99017eb80d88e345":{
      "scriptId":"u11"},
    "0084a714a1024256b79c9e60c6c252c9":{
      "scriptId":"u12"},
    "c576f0eebe414792915ad85bad37f251":{
      "scriptId":"u13"},
    "ed59fcfcf87d464780f4a242097966fe":{
      "scriptId":"u14"},
    "245f7e15eee242e2aa195859e25f6f5a":{
      "scriptId":"u15"},
    "2bf9cdbd7e8a4f318f277ab473893234":{
      "scriptId":"u16"},
    "370c4666cbca4e75b7e58ad973a7ee09":{
      "scriptId":"u17"},
    "47b6818a93394172bf6ea78c5f129fa5":{
      "scriptId":"u18"},
    "9e0e922127a947e498bfd194da68bcf8":{
      "scriptId":"u19"},
    "25a585acc73b4b1cbce40b1fc5343766":{
      "scriptId":"u20"},
    "9118d673f63940a3acb11ff0e1d26e29":{
      "scriptId":"u21"},
    "6607273a257c4dc2a86740de1c001046":{
      "scriptId":"u22"},
    "6c786f17d92143c2b67b29ffdafb6f27":{
      "scriptId":"u23"},
    "d4fe0c72647542e8b4fc3fad47156979":{
      "scriptId":"u24"},
    "c9fb518bce9d481abe03254425c01d74":{
      "scriptId":"u25"},
    "8c7696f3b78e4cd1bc4b913f4d4e0aa6":{
      "scriptId":"u26"},
    "571bb045d81f4100b8bd326dd3836ffb":{
      "scriptId":"u27"},
    "2f509475a7444cd2b158a2e6ebd862d3":{
      "scriptId":"u28"},
    "0a657e099e174e34ace127ba917463c2":{
      "scriptId":"u29"},
    "e9d11f18e66641279f17d26133e82f66":{
      "scriptId":"u30"},
    "51810f8b8f46487ea4544f96d04ec3fd":{
      "scriptId":"u31"},
    "e1fe80ab313544869d3c3e9607a1671e":{
      "scriptId":"u32"},
    "0e112c1170314113b144b3b49ea16745":{
      "scriptId":"u33"},
    "950251552b144a1eb8f359b6be8b0238":{
      "scriptId":"u34"},
    "a27418e88a4e413c93f1c950b9c59b8f":{
      "scriptId":"u35"},
    "fd52a9b7abf74844a657994f3659442c":{
      "scriptId":"u36"},
    "38a9b1ed89354b33a01cb7800ae1d218":{
      "scriptId":"u37"},
    "6c0e1eef53d3447295b4eb8f607c8322":{
      "scriptId":"u38"},
    "dcf0d0af149348a0986a4533cf63aca4":{
      "scriptId":"u39"},
    "cee38a3a6a574e63b3b79a19ea6f3c97":{
      "scriptId":"u40"},
    "d15d3bc2c95b4fccb4944d20e7fa0cbc":{
      "scriptId":"u41"},
    "987b56868c814d4f870c0102b99ef9c8":{
      "scriptId":"u42"},
    "c5246ec32c0841c0a675b63e241d2936":{
      "scriptId":"u43"},
    "343d7edc821b465d8be3b67b84b7ff4a":{
      "scriptId":"u44"},
    "4a4ac70f6dd74bdfb5a2a270e8c905e5":{
      "scriptId":"u45"},
    "15ab70087088413da77f18edcc44fa4d":{
      "scriptId":"u46"},
    "b4bd62ec9435484a89cf4886dd85d86a":{
      "scriptId":"u47"},
    "f30d69caf2d345d98339b723656ee466":{
      "scriptId":"u48"},
    "483e5a6c595b442fb08ca7c912e8db86":{
      "scriptId":"u49"},
    "a9c6ffb453c7449f84f91d32ec5cc757":{
      "scriptId":"u50"},
    "0e705852cee54d1482e9996c1c8c15dc":{
      "scriptId":"u51"},
    "fafc5e4330e148a2821896ac6b40b8f5":{
      "scriptId":"u52"},
    "8bbb9807c76f43a0a35e9a4980911adb":{
      "scriptId":"u53"},
    "f5c4fc15d9014a998f061b2cada42d36":{
      "scriptId":"u54"},
    "43dc435dc2314f829c39bd52e9f39f55":{
      "scriptId":"u55"},
    "5000f62f696d41868cce6c291b33d5ab":{
      "scriptId":"u56"},
    "420aff8a5d484b4cbbeaaf5844065f10":{
      "scriptId":"u57"},
    "07653451f07b40f0ba12736d820f68ab":{
      "scriptId":"u58"},
    "c0ffa053453b41cf8d3b4d744873ed90":{
      "scriptId":"u59"},
    "de267fa08ed64baba029a0a1f30a62e7":{
      "scriptId":"u60"},
    "4d5344a666f647f5b1b9a038877140e5":{
      "scriptId":"u61"},
    "0ae931178bc94e038d7b498e01f42cb3":{
      "scriptId":"u62"},
    "c6242164575742a69e6b3cc1fb2211c0":{
      "scriptId":"u63"}}});