$axure.loadCurrentPage({
  "url":"计算结果.html",
  "generationDate":new Date(1481800602965.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bb887b041047480cb7b71b5a58316165",
    "type":"Axure:Page",
    "name":"计算结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f23cb2cb13d48b2a0900d7ef35e2e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":347,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f35477708746c9a68a28cfa1df5131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":347,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算结果/u0.png"}},
{
          "id":"bab8e742ea2a4823a9f3011940de9739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":347,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc8d31593294be5a1d8774ffbcef9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":347,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算结果/u2.png"}},
{
          "id":"99865eedee6d4da1a3e26685fdbe686e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":276},
            "size":{
              "width":282,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ecb3ae52b3d4b2993f7eada979b03b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":59,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1596f666f3864e92a52452ff5f4e0f0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":59,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u5.png"}},
{
              "id":"aa21d093e8bc4c84a7b69b9411a71aa0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":59,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb62d7ae91f64b8797a6436f11d477c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":59,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u5.png"}},
{
              "id":"0a7be03634af4e8082b8764fd0a0dab5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":59,
                  "y":0},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6d2d4cec79b4e68bc8dcdfad9953c9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":59,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u7.png"}},
{
              "id":"e38856f476f34c0493337ce3df2fa6c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":59,
                  "y":30},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc4f596c7bba421e8c4bd5e9f64f8487",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":59,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u7.png"}},
{
              "id":"c3cc4f261f1a40639fbf5925f875c1b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":0},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd3e29a316a843318388af3aa9efaa07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":164,
                      "y":0},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u9.png"}},
{
              "id":"a0f869b08b624e909c0bfe5329b74885",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":30},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8727c9f0687f4dd9be51f27c1bc19ee1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":164,
                      "y":30},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u9.png"}},
{
              "id":"8751133c8f4f471ab15b52f53c7283a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":59,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6d92f94b11c4e6d905e0e1c6d3715f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":59,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u17.png"}},
{
              "id":"6eb7552168dc422f9e18ef926ad9137f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":59,
                  "y":60},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64376049a55e44a6a5327cf3bccfd40f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":59,
                      "y":60},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u19.png"}},
{
              "id":"2ccebdae95944dc9abc82a295092f875",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":60},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b481469e52124ebeba02cfd88ae4567f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":164,
                      "y":60},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u21.png"}}]},
{
          "id":"77962f40eac144b698fe7f8481253768",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":394},
            "size":{
              "width":282,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e3d1f2961154477950742d1d6810f89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":59,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ab42e758a164775851d0ba011fcc194",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":59,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u17.png"}},
{
              "id":"4cbcc92b44874755bd3ae728c2fc4750",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":59,
                  "y":0},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bdbab40172cd420f936502982c6ff4ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":59,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u19.png"}},
{
              "id":"0eb7f34182fd4fce8828576d11241cf5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":0},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7f720d4f227453abf98dbc85662fc07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":164,
                      "y":0},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/计算结果/u21.png"}}]},
{
          "id":"7d3beb68b5c6457689334d235ed2bf39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":250},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b6be51e1e74c0cabce3530ad102301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":250},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cf484761e854501a54b21aaa693cee7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":510},
            "size":{
              "width":189,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"129a8b34a09e4f12b701404c55b96296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":510},
                "size":{
                  "width":189,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d42010dfd90a4bea929d34b582b89e99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":259,
              "y":516},
            "size":{
              "width":79,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb2842d8fa764cf69916033401e9791f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":259,
                  "y":516},
                "size":{
                  "width":79,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e7c7255f4240b2a6c404b87ab9d939",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":55,
              "y":590},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32cd0e5d8d24a7c93b68ed1cf49c0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":55,
                  "y":590},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66ec36b7bb884a23a6b9eb279a5f1846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":142},
            "size":{
              "width":275,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fab64a153d34cbe831b45ae59f37214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":142},
                "size":{
                  "width":275,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c797f94c53e14e3caabb7287000140c5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":131,
              "y":623},
            "size":{
              "width":222,
              "height":37}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入房产信息",
                      "target":{
                        "targetType":"page",
                        "url":"输入房产信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f2158e1e71b148bfa1ffd103437bcf79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":269,
              "y":590},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a9d0a66e1942dbb636b941a6e0942b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":590},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef422fc474be4c09b3a943ea6ad68920",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0x26000000},
            "location":{
              "x":450,
              "y":124},
            "size":{
              "width":290,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6cd50418db54ee8975dbece863db7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0x26000000},
                "location":{
                  "x":450,
                  "y":124},
                "size":{
                  "width":290,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算结果/u43.png"}},
{
          "id":"d0bfecf75bf94f5394ef2195a3d8e16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":448,
              "y":120},
            "size":{
              "width":290,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28162a3815a846e99a011de13faa43e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":448,
                  "y":120},
                "size":{
                  "width":290,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算结果/u45.png"}},
{
          "id":"5607417b55414ba2a5392a1d004e1fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":347,
              "y":150},
            "size":{
              "width":101,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d455362ed646ada4de09b33ad2e020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":347,
                  "y":150},
                "size":{
                  "width":101,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算结果/u47.png"}},
{
          "id":"de396f3f569e4cd8b1ea0b3348fc55f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":454,
              "y":141},
            "size":{
              "width":279,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bada683edfc4505a33690e8b090152a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":454,
                  "y":141},
                "size":{
                  "width":279,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bc92848bebe439496bb150742ea8a5c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":442,
              "y":151},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/输入房产信息/u56_line.png"}},
{
          "id":"a3bfba49b4e246938da1f5b6fec85937",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":170,
              "y":690},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11895e697e77447b83f04784ffa9c129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":690},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfbeca88e3104eb88a1087edffb386eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0x26000000},
            "location":{
              "x":503,
              "y":682},
            "size":{
              "width":207,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3f5c90c5724ab186aa6147afc67a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0x26000000},
                "location":{
                  "x":503,
                  "y":682},
                "size":{
                  "width":207,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u57.png"}},
{
          "id":"272a232bc0b140b399fd788c9792e19a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":502,
              "y":680},
            "size":{
              "width":207,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7161b0ef0b1e467f86d20218a88ccb0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":502,
                  "y":680},
                "size":{
                  "width":207,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u59.png"}},
{
          "id":"b79df88001b6433ca58b29662ad60473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":340,
              "y":683},
            "size":{
              "width":164,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2167f617417f45dc8870bcebf06cca10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":340,
                  "y":683},
                "size":{
                  "width":164,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u54.png"}},
{
          "id":"42934ec3db954cb5811648369f9979b3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":494,
              "y":684},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/输入房产信息/u56_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f23cb2cb13d48b2a0900d7ef35e2e59":{
      "scriptId":"u0"},
    "22f35477708746c9a68a28cfa1df5131":{
      "scriptId":"u1"},
    "bab8e742ea2a4823a9f3011940de9739":{
      "scriptId":"u2"},
    "ebc8d31593294be5a1d8774ffbcef9ad":{
      "scriptId":"u3"},
    "99865eedee6d4da1a3e26685fdbe686e":{
      "scriptId":"u4"},
    "2ecb3ae52b3d4b2993f7eada979b03b7":{
      "scriptId":"u5"},
    "1596f666f3864e92a52452ff5f4e0f0d":{
      "scriptId":"u6"},
    "0a7be03634af4e8082b8764fd0a0dab5":{
      "scriptId":"u7"},
    "c6d2d4cec79b4e68bc8dcdfad9953c9d":{
      "scriptId":"u8"},
    "c3cc4f261f1a40639fbf5925f875c1b9":{
      "scriptId":"u9"},
    "fd3e29a316a843318388af3aa9efaa07":{
      "scriptId":"u10"},
    "aa21d093e8bc4c84a7b69b9411a71aa0":{
      "scriptId":"u11"},
    "cb62d7ae91f64b8797a6436f11d477c8":{
      "scriptId":"u12"},
    "e38856f476f34c0493337ce3df2fa6c4":{
      "scriptId":"u13"},
    "fc4f596c7bba421e8c4bd5e9f64f8487":{
      "scriptId":"u14"},
    "a0f869b08b624e909c0bfe5329b74885":{
      "scriptId":"u15"},
    "8727c9f0687f4dd9be51f27c1bc19ee1":{
      "scriptId":"u16"},
    "8751133c8f4f471ab15b52f53c7283a0":{
      "scriptId":"u17"},
    "d6d92f94b11c4e6d905e0e1c6d3715f8":{
      "scriptId":"u18"},
    "6eb7552168dc422f9e18ef926ad9137f":{
      "scriptId":"u19"},
    "64376049a55e44a6a5327cf3bccfd40f":{
      "scriptId":"u20"},
    "2ccebdae95944dc9abc82a295092f875":{
      "scriptId":"u21"},
    "b481469e52124ebeba02cfd88ae4567f":{
      "scriptId":"u22"},
    "77962f40eac144b698fe7f8481253768":{
      "scriptId":"u23"},
    "7e3d1f2961154477950742d1d6810f89":{
      "scriptId":"u24"},
    "9ab42e758a164775851d0ba011fcc194":{
      "scriptId":"u25"},
    "4cbcc92b44874755bd3ae728c2fc4750":{
      "scriptId":"u26"},
    "bdbab40172cd420f936502982c6ff4ac":{
      "scriptId":"u27"},
    "0eb7f34182fd4fce8828576d11241cf5":{
      "scriptId":"u28"},
    "b7f720d4f227453abf98dbc85662fc07":{
      "scriptId":"u29"},
    "7d3beb68b5c6457689334d235ed2bf39":{
      "scriptId":"u30"},
    "d5b6be51e1e74c0cabce3530ad102301":{
      "scriptId":"u31"},
    "6cf484761e854501a54b21aaa693cee7":{
      "scriptId":"u32"},
    "129a8b34a09e4f12b701404c55b96296":{
      "scriptId":"u33"},
    "d42010dfd90a4bea929d34b582b89e99":{
      "scriptId":"u34"},
    "eb2842d8fa764cf69916033401e9791f":{
      "scriptId":"u35"},
    "00e7c7255f4240b2a6c404b87ab9d939":{
      "scriptId":"u36"},
    "b32cd0e5d8d24a7c93b68ed1cf49c0b9":{
      "scriptId":"u37"},
    "66ec36b7bb884a23a6b9eb279a5f1846":{
      "scriptId":"u38"},
    "9fab64a153d34cbe831b45ae59f37214":{
      "scriptId":"u39"},
    "c797f94c53e14e3caabb7287000140c5":{
      "scriptId":"u40"},
    "f2158e1e71b148bfa1ffd103437bcf79":{
      "scriptId":"u41"},
    "75a9d0a66e1942dbb636b941a6e0942b":{
      "scriptId":"u42"},
    "ef422fc474be4c09b3a943ea6ad68920":{
      "scriptId":"u43"},
    "d6cd50418db54ee8975dbece863db7f6":{
      "scriptId":"u44"},
    "d0bfecf75bf94f5394ef2195a3d8e16c":{
      "scriptId":"u45"},
    "28162a3815a846e99a011de13faa43e0":{
      "scriptId":"u46"},
    "5607417b55414ba2a5392a1d004e1fd6":{
      "scriptId":"u47"},
    "e2d455362ed646ada4de09b33ad2e020":{
      "scriptId":"u48"},
    "de396f3f569e4cd8b1ea0b3348fc55f5":{
      "scriptId":"u49"},
    "0bada683edfc4505a33690e8b090152a":{
      "scriptId":"u50"},
    "3bc92848bebe439496bb150742ea8a5c":{
      "scriptId":"u51"},
    "a3bfba49b4e246938da1f5b6fec85937":{
      "scriptId":"u52"},
    "11895e697e77447b83f04784ffa9c129":{
      "scriptId":"u53"},
    "dfbeca88e3104eb88a1087edffb386eb":{
      "scriptId":"u54"},
    "7a3f5c90c5724ab186aa6147afc67a91":{
      "scriptId":"u55"},
    "272a232bc0b140b399fd788c9792e19a":{
      "scriptId":"u56"},
    "7161b0ef0b1e467f86d20218a88ccb0d":{
      "scriptId":"u57"},
    "b79df88001b6433ca58b29662ad60473":{
      "scriptId":"u58"},
    "2167f617417f45dc8870bcebf06cca10":{
      "scriptId":"u59"},
    "42934ec3db954cb5811648369f9979b3":{
      "scriptId":"u60"}}});