$axure.loadCurrentPage({
  "url":"选择小区.html",
  "generationDate":new Date(1481800603203.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"adf2b89882384ed8be2a9e04e2cf75bf",
    "type":"Axure:Page",
    "name":"选择小区",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8452732ad8cb4ee397a2d839e6379f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a30d79293d8f4afd8a7e91a76d702adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择小区/u0.png"}},
{
          "id":"e6dcbd3cf1e4464683e70b5f3c6a9bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e964bba4e8194e0c9cfc9e5c43691102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息/u2.png"}},
{
          "id":"69741cb3486c419eb252b43b4a2bd119",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":92},
            "size":{
              "width":344,
              "height":99},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096daf3a408d42a18a474305f329e7ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":92},
                "size":{
                  "width":344,
                  "height":99},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择小区/u4.png"}},
{
          "id":"c9fb6ef4ba474c439ad8f89c1f8d5733",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":191},
            "size":{
              "width":344,
              "height":33},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"2",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1701522c1caf42cd9bd53e7ebf179a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":191},
                "size":{
                  "width":344,
                  "height":33},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"2",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择楼栋号",
                      "target":{
                        "targetType":"page",
                        "url":"选择楼栋号.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择小区/u6.png"}},
{
          "id":"4f7bbf0e4919460d9461fe6d091ccd98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":224},
            "size":{
              "width":344,
              "height":96},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b468c8f5f13a466ca927c1f3aa7a2402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":224},
                "size":{
                  "width":344,
                  "height":96},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择小区/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8452732ad8cb4ee397a2d839e6379f44":{
      "scriptId":"u0"},
    "a30d79293d8f4afd8a7e91a76d702adb":{
      "scriptId":"u1"},
    "e6dcbd3cf1e4464683e70b5f3c6a9bc3":{
      "scriptId":"u2"},
    "e964bba4e8194e0c9cfc9e5c43691102":{
      "scriptId":"u3"},
    "69741cb3486c419eb252b43b4a2bd119":{
      "scriptId":"u4"},
    "096daf3a408d42a18a474305f329e7ac":{
      "scriptId":"u5"},
    "c9fb6ef4ba474c439ad8f89c1f8d5733":{
      "scriptId":"u6"},
    "1701522c1caf42cd9bd53e7ebf179a0d":{
      "scriptId":"u7"},
    "4f7bbf0e4919460d9461fe6d091ccd98":{
      "scriptId":"u8"},
    "b468c8f5f13a466ca927c1f3aa7a2402":{
      "scriptId":"u9"}}});