$axure.loadCurrentPage({
  "url":"产权查询结果.html",
  "generationDate":new Date(1481800603561.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"248e33262d15455a8f5cd6898ab30e6a",
    "type":"Axure:Page",
    "name":"产权查询结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12148943aabc4c049b8ca90574a22375",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2edd5e56702432ab9940bbbe0258d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产权查询结果/u0.png"}},
{
          "id":"eb81b49fdba24df081d25af93ffca37f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f84c83156ff043caa50606c662e07c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产权查询结果/u2.png"}},
{
          "id":"7bdac22d42e74e5fa1e255437ed1bf02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":128},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3246f69c3e2e4ed98a8c9e79c8c620bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":128},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07c100acdaee40ff9aca84837e9e43b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":159},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21bbb0157ca44f02b5d8db4ea5468025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":159},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5aaf662957e4c8aa1b23a843cfb5c6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":128},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e62e3fc2361742d4a8f98f6d2024ac61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":128},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c238710c511b4942b29f46d879fa7116",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":159},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd375c6e67e49ef94404a3bacd88381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":159},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41f36c5c6be44bbb6a825a204569771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":234},
            "size":{
              "width":275,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6964bfa9754d4637addbf19ac1a491b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":234},
                "size":{
                  "width":275,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c6bfaf12dc4dbcbd5f8ef88c3f4431",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":185},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac84f799b96943b1862e54a0e4cb168b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":185},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96e068b95cf8477ab29875b502b6a5fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":185},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a38779ba3fe49c4ad71e76ef515e1fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":185},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3288de5c0d2f49bfa047a2ef636fdfd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":208},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d2c15632e048e4b017ef6f5a6fce67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":208},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16389b57c9f848389ee170bebfcbd64b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":208},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275298b4ffdc44bca3e9ff99dba07a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":208},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d2e34faab2048a48a4a51159ca165da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":260},
            "size":{
              "width":325,
              "height":218}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1c5c8f02a5e4ed8b38ae75b88c09ff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":260},
                "size":{
                  "width":325,
                  "height":218}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产权查询结果/u22.png"}},
{
          "id":"808b3c34c6a5453aaa0f1de9ffa27c2c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":147.5,
              "y":498},
            "size":{
              "width":120,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 立即返回结果",
                      "target":{
                        "targetType":"page",
                        "url":"立即返回结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "12148943aabc4c049b8ca90574a22375":{
      "scriptId":"u0"},
    "c2edd5e56702432ab9940bbbe0258d74":{
      "scriptId":"u1"},
    "eb81b49fdba24df081d25af93ffca37f":{
      "scriptId":"u2"},
    "f84c83156ff043caa50606c662e07c42":{
      "scriptId":"u3"},
    "7bdac22d42e74e5fa1e255437ed1bf02":{
      "scriptId":"u4"},
    "3246f69c3e2e4ed98a8c9e79c8c620bf":{
      "scriptId":"u5"},
    "07c100acdaee40ff9aca84837e9e43b3":{
      "scriptId":"u6"},
    "21bbb0157ca44f02b5d8db4ea5468025":{
      "scriptId":"u7"},
    "b5aaf662957e4c8aa1b23a843cfb5c6a":{
      "scriptId":"u8"},
    "e62e3fc2361742d4a8f98f6d2024ac61":{
      "scriptId":"u9"},
    "c238710c511b4942b29f46d879fa7116":{
      "scriptId":"u10"},
    "0bd375c6e67e49ef94404a3bacd88381":{
      "scriptId":"u11"},
    "f41f36c5c6be44bbb6a825a204569771":{
      "scriptId":"u12"},
    "6964bfa9754d4637addbf19ac1a491b9":{
      "scriptId":"u13"},
    "f0c6bfaf12dc4dbcbd5f8ef88c3f4431":{
      "scriptId":"u14"},
    "ac84f799b96943b1862e54a0e4cb168b":{
      "scriptId":"u15"},
    "96e068b95cf8477ab29875b502b6a5fe":{
      "scriptId":"u16"},
    "7a38779ba3fe49c4ad71e76ef515e1fd":{
      "scriptId":"u17"},
    "3288de5c0d2f49bfa047a2ef636fdfd0":{
      "scriptId":"u18"},
    "07d2c15632e048e4b017ef6f5a6fce67":{
      "scriptId":"u19"},
    "16389b57c9f848389ee170bebfcbd64b":{
      "scriptId":"u20"},
    "275298b4ffdc44bca3e9ff99dba07a7c":{
      "scriptId":"u21"},
    "9d2e34faab2048a48a4a51159ca165da":{
      "scriptId":"u22"},
    "c1c5c8f02a5e4ed8b38ae75b88c09ff2":{
      "scriptId":"u23"},
    "808b3c34c6a5453aaa0f1de9ffa27c2c":{
      "scriptId":"u24"}}});