$axure.loadCurrentPage({
  "url":"微信通知查询结果页面-查询失败.html",
  "generationDate":new Date(1481800603621.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ba32ba17dcd474bbebf6ec057ba3e93",
    "type":"Axure:Page",
    "name":"微信通知查询结果页面-查询失败",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e13076bee1fe4b1f8f14fe7a47a32f56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":40},
            "size":{
              "width":506,
              "height":865}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"909323859ef64371b23f4e6d915cb022",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":40},
                "size":{
                  "width":506,
                  "height":865}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果-查询成功/u0.png"}},
{
          "id":"60588415e8a24063a5e274c5501d1f28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":296},
            "size":{
              "width":469,
              "height":373},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"850a5aaf0e234931b6a3d18877b363ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":296},
                "size":{
                  "width":469,
                  "height":373},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果页面-查询失败/u2.png"}},
{
          "id":"c9a879ca3f824970a9fb588792cdec44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":665},
            "size":{
              "width":469,
              "height":23},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf68a7857e2429d8462de4b67339fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":665},
                "size":{
                  "width":469,
                  "height":23},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信通知查询结果页面-查询失败/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e13076bee1fe4b1f8f14fe7a47a32f56":{
      "scriptId":"u0"},
    "909323859ef64371b23f4e6d915cb022":{
      "scriptId":"u1"},
    "60588415e8a24063a5e274c5501d1f28":{
      "scriptId":"u2"},
    "850a5aaf0e234931b6a3d18877b363ab":{
      "scriptId":"u3"},
    "c9a879ca3f824970a9fb588792cdec44":{
      "scriptId":"u4"},
    "bbf68a7857e2429d8462de4b67339fd9":{
      "scriptId":"u5"}}});