$axure.loadCurrentPage({
  "url":"评估价查询结果页面.html",
  "generationDate":new Date(1481800603322.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7021ed04c6f6409e83105997780a656d",
    "type":"Axure:Page",
    "name":"评估价查询结果页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7bd99da906f42d3b35a477d22928cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":387,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e11ec0e1386446980e43948c6220fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":387,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评估价查询结果页面/u0.png"}},
{
          "id":"537b123e39864ef58b2c6d922b3a8685",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":387,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"174f659c1fcd4b57a61eabd180b17f22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":387,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评估价查询结果页面/u2.png"}},
{
          "id":"08b8a7e4d98b483d963f8d58d00f838d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":91},
            "size":{
              "width":387,
              "height":61},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3674a2d5a047a08e5a59aaedf969c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":91},
                "size":{
                  "width":387,
                  "height":61},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评估价查询结果页面/u4.png"}},
{
          "id":"6efc49610e11419ca32697c1ce25972b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":196},
            "size":{
              "width":370,
              "height":145},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e02d8df8abd342bcab74ebde044f8105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":196},
                "size":{
                  "width":370,
                  "height":145},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评估价查询结果页面/u6.png"}},
{
          "id":"eeb8dd7fe3be4db38418e2f3b7d4f0af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":345},
            "size":{
              "width":370,
              "height":145},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0816d1911f4cf68647747217eecb47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":345},
                "size":{
                  "width":370,
                  "height":145},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评估价查询结果页面/u8.png"}},
{
          "id":"531d496e0c1540f8ba2fcabcde2503dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":160},
            "size":{
              "width":234,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c8debc83470474ebb3e84b43649c54f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":160},
                "size":{
                  "width":234,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e59fe586fc149d5a35b7cd171030b17",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":176.5,
              "y":540},
            "size":{
              "width":120,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入房产信息",
                      "target":{
                        "targetType":"page",
                        "url":"输入房产信息_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "a7bd99da906f42d3b35a477d22928cb1":{
      "scriptId":"u0"},
    "2e11ec0e1386446980e43948c6220fb6":{
      "scriptId":"u1"},
    "537b123e39864ef58b2c6d922b3a8685":{
      "scriptId":"u2"},
    "174f659c1fcd4b57a61eabd180b17f22":{
      "scriptId":"u3"},
    "08b8a7e4d98b483d963f8d58d00f838d":{
      "scriptId":"u4"},
    "3f3674a2d5a047a08e5a59aaedf969c3":{
      "scriptId":"u5"},
    "6efc49610e11419ca32697c1ce25972b":{
      "scriptId":"u6"},
    "e02d8df8abd342bcab74ebde044f8105":{
      "scriptId":"u7"},
    "eeb8dd7fe3be4db38418e2f3b7d4f0af":{
      "scriptId":"u8"},
    "9f0816d1911f4cf68647747217eecb47":{
      "scriptId":"u9"},
    "531d496e0c1540f8ba2fcabcde2503dc":{
      "scriptId":"u10"},
    "6c8debc83470474ebb3e84b43649c54f":{
      "scriptId":"u11"},
    "2e59fe586fc149d5a35b7cd171030b17":{
      "scriptId":"u12"}}});