$axure.loadCurrentPage({
  "url":"选择楼栋号.html",
  "generationDate":new Date(1481800603244.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9610492538c44866b0f776103372653b",
    "type":"Axure:Page",
    "name":"选择楼栋号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ac6523edf5b4192a14f34a62e2516af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd9c920b04e48738b83ecda20c2d3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择楼栋号/u0.png"}},
{
          "id":"7a645ab0679a485e9e88c794a65ccd10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6d539bdd460403e8438d5dd80bfdd34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择楼栋号/u2.png"}},
{
          "id":"537066851f0e491891f2b532c8caf60a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":147},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a5993514b54462c8721ccdff194a7eb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":252},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"33bc190cec56404eb53c1662f092e744",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":282},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"56847e7f244e40168a4f63ba5ca2221e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":319},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b48f1a7935e412897436cbb1f8033fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":319},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6b4470e06ae84027a137fa14ed5de5a7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":319},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ae13526e6e4f748b348a146f4d7372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":319},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"96570249848f4b7884eb96ca0c486c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":319},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b669eff9cd7643f4907642106ab9bea6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":319},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e689a6f3069940a9bba6498efd2ee953",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":357},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807a4e78f0dd4624a8cc64259e08393a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":357},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c4c4c3f2c8ce4aad87933fdd1f716512",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":357},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2526ce6375a748e4b52643c40a4b273c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":357},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7fd8bb7fb4424a44a5032c2f9ae6d1b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":357},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2431906ae6a645f5b917c8a27fc9ca0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":357},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3664b5f98414a53be5eb0efcd32d5de",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":391},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae74c94d1f446a4b6a219813b3424f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":391},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0f847de71d144219b437719f70370b7e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":391},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc69bcbc51ac4fa2b54c26e5b8321643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":391},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"71d993fe1aeb4eae92054140bb7d7f12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":391},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceaf79a8628244f8a9864cce0d6033fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":391},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8c38c933d0446b29c2248ab64cd0833",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":432},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 稍后返回查询结果",
                      "target":{
                        "targetType":"page",
                        "url":"稍后返回查询结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aba1440519da4d34aff24dacaa1ef806",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":205,
              "y":474},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b273d9847c4a80a24066e3594d884c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":474},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查询历史记录页面",
                      "target":{
                        "targetType":"page",
                        "url":"查询历史记录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4de1b7f2166d470399e8bb1860c1e219",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":186},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"583fb8ca47fe4c548a8ad9f312d6b33d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":219},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f2b7172ec824a7e9b6c19cf7b8ae571",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":100},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"feb4694883ed4acab90555b91386c294",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":103},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f527e34f4947e18a5cf8a3fcedc5d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":103},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36d28ce66b6e4893959d9696065862b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":126},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0ca249d2854ef2819b37a7d6cbc0d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":126},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1ac6523edf5b4192a14f34a62e2516af":{
      "scriptId":"u0"},
    "ecd9c920b04e48738b83ecda20c2d3d3":{
      "scriptId":"u1"},
    "7a645ab0679a485e9e88c794a65ccd10":{
      "scriptId":"u2"},
    "b6d539bdd460403e8438d5dd80bfdd34":{
      "scriptId":"u3"},
    "537066851f0e491891f2b532c8caf60a":{
      "scriptId":"u4"},
    "2a5993514b54462c8721ccdff194a7eb":{
      "scriptId":"u5"},
    "33bc190cec56404eb53c1662f092e744":{
      "scriptId":"u6"},
    "56847e7f244e40168a4f63ba5ca2221e":{
      "scriptId":"u7"},
    "5b48f1a7935e412897436cbb1f8033fe":{
      "scriptId":"u8"},
    "6b4470e06ae84027a137fa14ed5de5a7":{
      "scriptId":"u9"},
    "00ae13526e6e4f748b348a146f4d7372":{
      "scriptId":"u10"},
    "96570249848f4b7884eb96ca0c486c9f":{
      "scriptId":"u11"},
    "b669eff9cd7643f4907642106ab9bea6":{
      "scriptId":"u12"},
    "e689a6f3069940a9bba6498efd2ee953":{
      "scriptId":"u13"},
    "807a4e78f0dd4624a8cc64259e08393a":{
      "scriptId":"u14"},
    "c4c4c3f2c8ce4aad87933fdd1f716512":{
      "scriptId":"u15"},
    "2526ce6375a748e4b52643c40a4b273c":{
      "scriptId":"u16"},
    "7fd8bb7fb4424a44a5032c2f9ae6d1b8":{
      "scriptId":"u17"},
    "2431906ae6a645f5b917c8a27fc9ca0d":{
      "scriptId":"u18"},
    "e3664b5f98414a53be5eb0efcd32d5de":{
      "scriptId":"u19"},
    "6ae74c94d1f446a4b6a219813b3424f5":{
      "scriptId":"u20"},
    "0f847de71d144219b437719f70370b7e":{
      "scriptId":"u21"},
    "fc69bcbc51ac4fa2b54c26e5b8321643":{
      "scriptId":"u22"},
    "71d993fe1aeb4eae92054140bb7d7f12":{
      "scriptId":"u23"},
    "ceaf79a8628244f8a9864cce0d6033fd":{
      "scriptId":"u24"},
    "a8c38c933d0446b29c2248ab64cd0833":{
      "scriptId":"u25"},
    "aba1440519da4d34aff24dacaa1ef806":{
      "scriptId":"u26"},
    "98b273d9847c4a80a24066e3594d884c":{
      "scriptId":"u27"},
    "4de1b7f2166d470399e8bb1860c1e219":{
      "scriptId":"u28"},
    "583fb8ca47fe4c548a8ad9f312d6b33d":{
      "scriptId":"u29"},
    "0f2b7172ec824a7e9b6c19cf7b8ae571":{
      "scriptId":"u30"},
    "feb4694883ed4acab90555b91386c294":{
      "scriptId":"u31"},
    "f5f527e34f4947e18a5cf8a3fcedc5d3":{
      "scriptId":"u32"},
    "36d28ce66b6e4893959d9696065862b4":{
      "scriptId":"u33"},
    "bb0ca249d2854ef2819b37a7d6cbc0d5":{
      "scriptId":"u34"}}});