$axure.loadCurrentPage({
  "url":"查询历史记录页面.html",
  "generationDate":new Date(1481800603413.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fa0d096742814b209fd87e1f979e8041",
    "type":"Axure:Page",
    "name":"查询历史记录页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90cb062ddd48436fa3b41a2dc329db1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":20},
            "size":{
              "width":347,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2adb72762b074733836e86fdf30b4b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":20},
                "size":{
                  "width":347,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询历史记录页面/u0.png"}},
{
          "id":"c07a4eedd46846faa4de925a7312da5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":67,
              "y":20},
            "size":{
              "width":347,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"954ab78a427347588f27c0542261014e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":67,
                  "y":20},
                "size":{
                  "width":347,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查询历史记录页面/u2.png"}},
{
          "id":"660c392ab3814dc3a20f3489a4c17eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":67,
              "y":104},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83c9753ee37945319ef6b2d7b23501b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":67,
                  "y":104},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 二次确认弹框 to 展示弹框",
                      "panelsToStates":[{
                          "panelPath":["a26d52eec1a6406fb5b3c758ec1a98a0"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"5094b1d8f23641a2b8ba9456f537207f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":390,
              "y":132},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83c3d65402114325ae961b3f01cde978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":390,
                  "y":132},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"945a137140454e8d9969b5fe754dca42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":81,
              "y":110},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9cc43ab13648bc94d609f111559429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":81,
                  "y":110},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8842d285aa3d48a6bf5fc0c45956087e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":81,
              "y":154},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30797ec86cd647c393d416ef72bebf14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":154},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6027e1c168164b12af1a110ed175ba42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":85,
              "y":68},
            "size":{
              "width":310,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ee1f4e907e24a29bbc50d541fcfcb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":85,
                  "y":68},
                "size":{
                  "width":310,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c636846eb0034ef4b4a22b29686f28ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":137},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b28dbc89f884f97bfaeab3bbdb91b15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":137},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1d4d76fff1a481f9d9b530223f806fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":67,
              "y":181},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e4f010daaa420096fa6a3b7b4a1665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":67,
                  "y":181},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"f0915a266f3b4e8ab853b4a318b067e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":390,
              "y":209},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96507a929c394ae1a9eeefeb86821c2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":390,
                  "y":209},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6cf6c23424f45e399ba299eb6bee5b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":81,
              "y":187},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf4d0e22d164c76a2238428728e1e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":81,
                  "y":187},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20955b45cd41451793c87063663d80a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":81,
              "y":231},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c3120ae5184a1caf9867fbcb899f82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":231},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38dbf9b9219d4b7bb40caa757332a57d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1634809fa45e46bab87479fd0fc0fa89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e7f3716c9d742c8863e6548a2b8d476",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":67,
              "y":258},
            "size":{
              "width":347,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e78f566d896e495ea344bfa196b4eea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":67,
                  "y":258},
                "size":{
                  "width":347,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/算税费的历史记录/u4.png"}},
{
          "id":"efe76b7a3548458182961d24d6500393",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":390,
              "y":286},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b431508d5d4c23b4d7a306d45d76b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":390,
                  "y":286},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f41d6c1fd3f4b469f52779d458285ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":81,
              "y":264},
            "size":{
              "width":203,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b710a92c14b84513958e1ae4cac8e2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":81,
                  "y":264},
                "size":{
                  "width":203,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a5fbf9ed6504530b7fd2149e6751710",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":81,
              "y":308},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbfbcc31e9ec4c3db6ecb349c6a3a3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":308},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5205d5bb7dd49d8934e79e4c0da6776",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":291},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3fe9a274b2b4f649c9d62e18f6567db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":291},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a26d52eec1a6406fb5b3c758ec1a98a0",
          "label":"二次确认弹框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":167},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0a1322ca67e74fe9b0b4c19d373c895a",
              "label":"隐藏弹框",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"c6ee96ba3698406788ac8c83697ca337",
              "label":"展示弹框",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"53b8efc937794763bca3fed5cccd1841",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":326,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2b82612982842d1a65860099b9418c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":326,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查询历史记录页面/u37.png"}},
{
                  "id":"fbd7e2fde1134ac6aa13aae616c6a012",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"17px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":32,
                      "y":91},
                    "size":{
                      "width":262,
                      "height":41},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0e2e060af48443e9ca225688e790a99",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"17px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":32,
                          "y":91},
                        "size":{
                          "width":262,
                          "height":41},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"59f3c86b63154846ad5ba37b4d36339e",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":20,
                      "y":148},
                    "size":{
                      "width":145,
                      "height":52}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93ad7c74798548c3964d89868d40248b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":20,
                          "y":148},
                        "size":{
                          "width":145,
                          "height":52}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查询历史记录页面/u41.png"}},
{
                  "id":"be6d3369f05c44f9876411b14b4dbaab",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Droid Sans Regular', 'Droid Sans'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":25,
                      "y":154},
                    "size":{
                      "width":135,
                      "height":39},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88cd0b92bc9c489492dded167a20975d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Droid Sans Regular', 'Droid Sans'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":25,
                          "y":154},
                        "size":{
                          "width":135,
                          "height":39},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 二次确认弹框 to 隐藏弹框",
                              "panelsToStates":[{
                                  "panelPath":["a26d52eec1a6406fb5b3c758ec1a98a0"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f89aaa256c6340b09b9f68f980c964c3",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":162,
                      "y":148},
                    "size":{
                      "width":145,
                      "height":52}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85bb927ad6084083807f85762442d405",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":162,
                          "y":148},
                        "size":{
                          "width":145,
                          "height":52}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查询历史记录页面/u41.png"}},
{
                  "id":"ed9c1cdb47ae459589871f203ca7a354",
                  "label":"",
                  "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Droid Sans Regular', 'Droid Sans'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":154},
                    "size":{
                      "width":131,
                      "height":40},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b22ff2be9a944e69946e01d222156fb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a26d52eec1a6406fb5b3c758ec1a98a0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Droid Sans Regular', 'Droid Sans'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":169,
                          "y":154},
                        "size":{
                          "width":131,
                          "height":40},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 稍后返回查询结果",
                              "target":{
                                "targetType":"page",
                                "url":"稍后返回查询结果.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "90cb062ddd48436fa3b41a2dc329db1e":{
      "scriptId":"u0"},
    "2adb72762b074733836e86fdf30b4b5c":{
      "scriptId":"u1"},
    "c07a4eedd46846faa4de925a7312da5a":{
      "scriptId":"u2"},
    "954ab78a427347588f27c0542261014e":{
      "scriptId":"u3"},
    "660c392ab3814dc3a20f3489a4c17eb3":{
      "scriptId":"u4"},
    "83c9753ee37945319ef6b2d7b23501b0":{
      "scriptId":"u5"},
    "5094b1d8f23641a2b8ba9456f537207f":{
      "scriptId":"u6"},
    "83c3d65402114325ae961b3f01cde978":{
      "scriptId":"u7"},
    "945a137140454e8d9969b5fe754dca42":{
      "scriptId":"u8"},
    "ab9cc43ab13648bc94d609f111559429":{
      "scriptId":"u9"},
    "8842d285aa3d48a6bf5fc0c45956087e":{
      "scriptId":"u10"},
    "30797ec86cd647c393d416ef72bebf14":{
      "scriptId":"u11"},
    "6027e1c168164b12af1a110ed175ba42":{
      "scriptId":"u12"},
    "1ee1f4e907e24a29bbc50d541fcfcb84":{
      "scriptId":"u13"},
    "c636846eb0034ef4b4a22b29686f28ca":{
      "scriptId":"u14"},
    "5b28dbc89f884f97bfaeab3bbdb91b15":{
      "scriptId":"u15"},
    "e1d4d76fff1a481f9d9b530223f806fa":{
      "scriptId":"u16"},
    "61e4f010daaa420096fa6a3b7b4a1665":{
      "scriptId":"u17"},
    "f0915a266f3b4e8ab853b4a318b067e0":{
      "scriptId":"u18"},
    "96507a929c394ae1a9eeefeb86821c2c":{
      "scriptId":"u19"},
    "c6cf6c23424f45e399ba299eb6bee5b9":{
      "scriptId":"u20"},
    "5bf4d0e22d164c76a2238428728e1e7a":{
      "scriptId":"u21"},
    "20955b45cd41451793c87063663d80a7":{
      "scriptId":"u22"},
    "85c3120ae5184a1caf9867fbcb899f82":{
      "scriptId":"u23"},
    "38dbf9b9219d4b7bb40caa757332a57d":{
      "scriptId":"u24"},
    "1634809fa45e46bab87479fd0fc0fa89":{
      "scriptId":"u25"},
    "7e7f3716c9d742c8863e6548a2b8d476":{
      "scriptId":"u26"},
    "e78f566d896e495ea344bfa196b4eea5":{
      "scriptId":"u27"},
    "efe76b7a3548458182961d24d6500393":{
      "scriptId":"u28"},
    "32b431508d5d4c23b4d7a306d45d76b4":{
      "scriptId":"u29"},
    "4f41d6c1fd3f4b469f52779d458285ca":{
      "scriptId":"u30"},
    "b710a92c14b84513958e1ae4cac8e2b7":{
      "scriptId":"u31"},
    "5a5fbf9ed6504530b7fd2149e6751710":{
      "scriptId":"u32"},
    "fbfbcc31e9ec4c3db6ecb349c6a3a3a9":{
      "scriptId":"u33"},
    "e5205d5bb7dd49d8934e79e4c0da6776":{
      "scriptId":"u34"},
    "f3fe9a274b2b4f649c9d62e18f6567db":{
      "scriptId":"u35"},
    "a26d52eec1a6406fb5b3c758ec1a98a0":{
      "scriptId":"u36"},
    "53b8efc937794763bca3fed5cccd1841":{
      "scriptId":"u37"},
    "b2b82612982842d1a65860099b9418c7":{
      "scriptId":"u38"},
    "fbd7e2fde1134ac6aa13aae616c6a012":{
      "scriptId":"u39"},
    "e0e2e060af48443e9ca225688e790a99":{
      "scriptId":"u40"},
    "59f3c86b63154846ad5ba37b4d36339e":{
      "scriptId":"u41"},
    "93ad7c74798548c3964d89868d40248b":{
      "scriptId":"u42"},
    "be6d3369f05c44f9876411b14b4dbaab":{
      "scriptId":"u43"},
    "88cd0b92bc9c489492dded167a20975d":{
      "scriptId":"u44"},
    "f89aaa256c6340b09b9f68f980c964c3":{
      "scriptId":"u45"},
    "85bb927ad6084083807f85762442d405":{
      "scriptId":"u46"},
    "ed9c1cdb47ae459589871f203ca7a354":{
      "scriptId":"u47"},
    "b22ff2be9a944e69946e01d222156fb9":{
      "scriptId":"u48"}}});