$axure.loadCurrentPage({
  "url":"输入房产信息_1.html",
  "generationDate":new Date(1481800603167.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"915bf32a611b40cebe8b66c6ca605334",
    "type":"Axure:Page",
    "name":"输入房产信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"71fbf373e61f4eca8546f173b628131f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0024c2e86382474090dab99629fe4bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息_1/u0.png"}},
{
          "id":"a7dcdb1960c2411d8dc9a94d5879efa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":347,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6fe4d0b25445ae969ad719a1c2c9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":347,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入房产信息_1/u2.png"}},
{
          "id":"b26a0fca635640dd8dfe9dbb865fa115",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":156},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择小区",
                      "target":{
                        "targetType":"page",
                        "url":"选择小区.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"038b5ba34dca4f3797d095c6af8a4251",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":196},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e46b01b02621482f86902195d89cfffc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF818181,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":236},
            "size":{
              "width":225,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"97a17d7351c94d8b914ee2dca4678c7b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":280},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd062eba3994b1e8bd406472fd3ec91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":280},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1f030eb31929438f94e04395f87e6b2d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":280},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7105ee00d2b4d85bab9dc903bea0114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":280},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"014a6762a41240eb814e64ebab87e9a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":280},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28f9cd937f23431fa2df7c975dbf790c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":280},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0159c105928e45388b709fc42aadce3e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":318},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeebc2f92cf04bea916e361e15f1410d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":318},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"48143dab6af546efa26a62857dcfdff5",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":318},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72b03c3408384e008e310ad441bd53b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":318},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4022f626b6744b59a6cbdb73b7da8298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":318},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95f712cc48341a0a5de3cee1d3a6d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":318},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a394d6eadfb04565884676f1d6faa714",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":352},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302415c816e745e5a42269e90798600d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":352},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0b27dd68d20444a88aa19323accc5846",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":352},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d98eeb6cb0d14e8dbd96054acde7a484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":352},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f6669b0a61d140f5b9d8b6363a086daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":352},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9865035fcdfa4df2bae681fc987bfc23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":352},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4b85bd294cd46a1b722d1298d5f3674",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":393},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a859a1685274e2595b49eb614523ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":207.5,
              "y":444},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efabb2323faa4391b7803cc5019225f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":207.5,
                  "y":444},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查询历史记录页面",
                      "target":{
                        "targetType":"page",
                        "url":"查询历史记录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b25d294759443e48743dec3e634b47d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":102},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ad51c9136b7c41eb86f4dd8b91d0c27e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":105},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b39b58656424bee82435a0f6ea53c99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":105},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5401fb7d56dd4d829f6bae7b7b8eb4d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":128},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d00256b8c94f13a4eebd42ee9356fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":128},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "71fbf373e61f4eca8546f173b628131f":{
      "scriptId":"u0"},
    "0024c2e86382474090dab99629fe4bc2":{
      "scriptId":"u1"},
    "a7dcdb1960c2411d8dc9a94d5879efa0":{
      "scriptId":"u2"},
    "4d6fe4d0b25445ae969ad719a1c2c9bb":{
      "scriptId":"u3"},
    "b26a0fca635640dd8dfe9dbb865fa115":{
      "scriptId":"u4"},
    "038b5ba34dca4f3797d095c6af8a4251":{
      "scriptId":"u5"},
    "e46b01b02621482f86902195d89cfffc":{
      "scriptId":"u6"},
    "97a17d7351c94d8b914ee2dca4678c7b":{
      "scriptId":"u7"},
    "7bd062eba3994b1e8bd406472fd3ec91":{
      "scriptId":"u8"},
    "1f030eb31929438f94e04395f87e6b2d":{
      "scriptId":"u9"},
    "b7105ee00d2b4d85bab9dc903bea0114":{
      "scriptId":"u10"},
    "014a6762a41240eb814e64ebab87e9a4":{
      "scriptId":"u11"},
    "28f9cd937f23431fa2df7c975dbf790c":{
      "scriptId":"u12"},
    "0159c105928e45388b709fc42aadce3e":{
      "scriptId":"u13"},
    "aeebc2f92cf04bea916e361e15f1410d":{
      "scriptId":"u14"},
    "48143dab6af546efa26a62857dcfdff5":{
      "scriptId":"u15"},
    "72b03c3408384e008e310ad441bd53b6":{
      "scriptId":"u16"},
    "4022f626b6744b59a6cbdb73b7da8298":{
      "scriptId":"u17"},
    "f95f712cc48341a0a5de3cee1d3a6d11":{
      "scriptId":"u18"},
    "a394d6eadfb04565884676f1d6faa714":{
      "scriptId":"u19"},
    "302415c816e745e5a42269e90798600d":{
      "scriptId":"u20"},
    "0b27dd68d20444a88aa19323accc5846":{
      "scriptId":"u21"},
    "d98eeb6cb0d14e8dbd96054acde7a484":{
      "scriptId":"u22"},
    "f6669b0a61d140f5b9d8b6363a086daf":{
      "scriptId":"u23"},
    "9865035fcdfa4df2bae681fc987bfc23":{
      "scriptId":"u24"},
    "e4b85bd294cd46a1b722d1298d5f3674":{
      "scriptId":"u25"},
    "2a859a1685274e2595b49eb614523ced":{
      "scriptId":"u26"},
    "efabb2323faa4391b7803cc5019225f3":{
      "scriptId":"u27"},
    "2b25d294759443e48743dec3e634b47d":{
      "scriptId":"u28"},
    "ad51c9136b7c41eb86f4dd8b91d0c27e":{
      "scriptId":"u29"},
    "7b39b58656424bee82435a0f6ea53c99":{
      "scriptId":"u30"},
    "5401fb7d56dd4d829f6bae7b7b8eb4d7":{
      "scriptId":"u31"},
    "00d00256b8c94f13a4eebd42ee9356fb":{
      "scriptId":"u32"}}});