$axure.loadCurrentPage({
  "url":"稍后返回查询结果_1.html",
  "generationDate":new Date(1481800603590.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d16af66686c74e3e845f648259987f4c",
    "type":"Axure:Page",
    "name":"稍后返回查询结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e964926e96e0430c805d1999e509c969",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11c26de463c4bcf8d831c63373d7018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u0.png"}},
{
          "id":"c3228fcd2c144b839b65b8890fff5ee8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf6f927a0c74be6bbd321c0726c0a70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u2.png"}},
{
          "id":"11f4e8efe02641bb90d65a9fa5a18dc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":201.5,
              "y":120},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f46de41d4b49405f86aecd5074b29792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":201.5,
                  "y":120},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u4.png"}},
{
          "id":"df7126efc89d4528abe62d31ae808a97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":123,
              "y":191},
            "size":{
              "width":177,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6522c164794b29bab675a37c891065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":123,
                  "y":191},
                "size":{
                  "width":177,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2584fbac505d48e8aa10d5a94a02dfce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":84,
              "y":233},
            "size":{
              "width":266,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55a7c3c81234f7d8b204d41ad3f84c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":84,
                  "y":233},
                "size":{
                  "width":266,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"519d31ee9aab43578c8a9b94b293ddf7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":164,
              "y":340},
            "size":{
              "width":120,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 立即返回结果",
                      "target":{
                        "targetType":"page",
                        "url":"立即返回结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e964926e96e0430c805d1999e509c969":{
      "scriptId":"u0"},
    "f11c26de463c4bcf8d831c63373d7018":{
      "scriptId":"u1"},
    "c3228fcd2c144b839b65b8890fff5ee8":{
      "scriptId":"u2"},
    "0bf6f927a0c74be6bbd321c0726c0a70":{
      "scriptId":"u3"},
    "11f4e8efe02641bb90d65a9fa5a18dc9":{
      "scriptId":"u4"},
    "f46de41d4b49405f86aecd5074b29792":{
      "scriptId":"u5"},
    "df7126efc89d4528abe62d31ae808a97":{
      "scriptId":"u6"},
    "9d6522c164794b29bab675a37c891065":{
      "scriptId":"u7"},
    "2584fbac505d48e8aa10d5a94a02dfce":{
      "scriptId":"u8"},
    "b55a7c3c81234f7d8b204d41ad3f84c5":{
      "scriptId":"u9"},
    "519d31ee9aab43578c8a9b94b293ddf7":{
      "scriptId":"u10"}}});