$axure.loadCurrentPage({
  "url":"稍后返回查询结果.html",
  "generationDate":new Date(1481800603279.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b6f876de02634ec8a4440185f1e0e650",
    "type":"Axure:Page",
    "name":"稍后返回查询结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2603fa3ca64d4b21a0fcf462db138b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea0e14d0b5c4c9cb36000ce5b0016af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u0.png"}},
{
          "id":"63d61b5e08e044acbf1562cd255588ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":43,
              "y":30},
            "size":{
              "width":347,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e40a8dcbee4e0c83b224c2d71b38a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":43,
                  "y":30},
                "size":{
                  "width":347,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u2.png"}},
{
          "id":"2c108e44544d4465b9cee239c0f2a951",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":202,
              "y":120},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e51c540fbd42c392f6146de9359d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":202,
                  "y":120},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/稍后返回查询结果/u4.png"}},
{
          "id":"26d4feb9a1524befb85039dcf2976579",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":123,
              "y":191},
            "size":{
              "width":177,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac54a7408b5a4101a83e5592f9667fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":123,
                  "y":191},
                "size":{
                  "width":177,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"def7b7079cbc4803afb59ba45d3942cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":84,
              "y":233},
            "size":{
              "width":266,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0448ae359c4a8586536e548ee57e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":84,
                  "y":233},
                "size":{
                  "width":266,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e00dc7692ee468ca35fc2547c91e1ea",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":164,
              "y":340},
            "size":{
              "width":120,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入房产信息",
                      "target":{
                        "targetType":"page",
                        "url":"输入房产信息_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "2603fa3ca64d4b21a0fcf462db138b39":{
      "scriptId":"u0"},
    "cea0e14d0b5c4c9cb36000ce5b0016af":{
      "scriptId":"u1"},
    "63d61b5e08e044acbf1562cd255588ed":{
      "scriptId":"u2"},
    "22e40a8dcbee4e0c83b224c2d71b38a6":{
      "scriptId":"u3"},
    "2c108e44544d4465b9cee239c0f2a951":{
      "scriptId":"u4"},
    "98e51c540fbd42c392f6146de9359d47":{
      "scriptId":"u5"},
    "26d4feb9a1524befb85039dcf2976579":{
      "scriptId":"u6"},
    "ac54a7408b5a4101a83e5592f9667fcb":{
      "scriptId":"u7"},
    "def7b7079cbc4803afb59ba45d3942cc":{
      "scriptId":"u8"},
    "2f0448ae359c4a8586536e548ee57e66":{
      "scriptId":"u9"},
    "6e00dc7692ee468ca35fc2547c91e1ea":{
      "scriptId":"u10"}}});